### ISSUE TITLE
gepard

### ISSUE THREAD

**Issue by duhuipeng** [univieCUBE/gepard#6] opened 2021-12-20 08:40 UTC
Dear author
![image](https://user-images.githubusercontent.com/58722433/146737640-c38f0f28-c96a-44b1-a37a-1c64c1cf7d43.png)
what should I do ?

Best
HuipengDu

**Comment by JulleeeK** [comment] 2021-12-20 08:45
Dear Huipeng Du,

 which version of Gepard are you using and on which system? Also, which java version are you using?

Best,
Julius

**Comment by duhuipeng** [comment] 2021-12-20 08:47
![image](https://user-images.githubusercontent.com/58722433/146738730-9e3f59b0-9e38-457d-b2a3-43d96b8a805c.png)

**Comment by duhuipeng** [comment] 2021-12-20 08:49
Dear author
![image](https://user-images.githubusercontent.com/58722433/146739028-c822bd1c-ccca-4949-b0b2-2a4a3ee71dc6.png)

this is gepard by conda install

**Comment by duhuipeng** [comment] 2021-12-20 08:54
Dear author 
could you help me ?Where do I have problems with the operation.
the matrix I also don t know how to generate it, and I used the matrix in the githup you provided?
Can I operate like this?

Best
HuipengDu

**Comment by JulleeeK** [comment] 2021-12-20 08:57
Dear Huipeng Du,

There is a version 2.1 available. Maybe you could try updating? In Your error log it states not X11 variable is set. I am assuming you are using Linux. Try the solution on this post: https://stackoverflow.com/questions/662421/no-x11-display-variable-what-does-it-mean

Best,
Julius

**Comment by duhuipeng** [comment] 2021-12-20 09:08
Dear author
![image](https://user-images.githubusercontent.com/58722433/146741404-5124e233-fc64-41fb-8037-b16d697d2057.png)
I added this operation but am still reporting the error and how can I fix it?(as follow)
![image](https://user-images.githubusercontent.com/58722433/146741618-e991f1b9-1f36-453b-8e11-b6984778361e.png)

Best
HuipengDu

**Comment by duhuipeng** [comment] 2021-12-20 09:13
Dear author
Could have fit into my java version of the gepard ?
Best
Duhuipeng

**Comment by duhuipeng** [comment] 2021-12-20 09:33
Dear author 
![image](https://user-images.githubusercontent.com/58722433/146745023-5ce7f613-dc23-48e2-b6c3-ef7dca7f8011.png)
I installed your old version but he still came from pressing this question, what should I do ?

Best
HuipengDu

**Comment by rattei** [comment] 2021-12-20 09:56
This is seemingly a duplicate of another issue: https://github.com/univieCUBE/gepard/issues/1

**Comment by rattei** [comment] 2021-12-20 09:56
Same answer als already given in the other issue:

When you run the gepard application from the command line, as explained in the readme.txt, it shows the usage:

java -cp dist/Gepard-1.40.jar org.gepard.client.cmdline.CommandLine

Gepard 1.40 final - command line mode

Reference:
Krumsiek J, Arnold R, Rattei T
Gepard: A rapid and sensitive tool for creating dotplots on genome scale.
Bioinformatics 2007; 23(8): 1026-8. PMID: 17309896

Parameters are supplied as -name value

Required parameters:
  -seq1:        first sequence file
  -seq2:        second sequence file
  -matrix:      substitution matrix file
  -outfile:     output file name

Dotplot image parameters:
  -maxwidth:    maximum width of the generated image (default: 750)
  -maxheight:   maximum height of the generated image (default: 750)
  -zoom:        specify a zoom factor for the dotplot
  note: you can only use maxwidth/maxheight OR zoom
        when using maxwidth/maxheight the program tries to generate the largest
        possible dotplot within the given bounds
  -format:      output format, one of:  'png', 'jpg', 'bmp' (default:PNG)

Dotplot computation parameters:
  -secondcomp   use complementary of second sequence
  -word:        word length for suffix array mode (default: 10)
  -window:      window size for ordinary dotplot mode (default: 0)
  if a window value and no word value is specified, word=0 is assumed

Suffix array parameters:
  -safile       load suffix array from file instead of calculating it
  -sasecondseq  the suffix array is for the second sequence
  if -sasecondseq is NOT specified, the suffix array will be used for first sequence

Coordinate parameters (absolute values of % values)
  -from1,-to1   coordinates of first sequence
  -from2,-to2   coordinates of second sequence
  if these parameters are not specified the full sequence will be used

Display parameters:
  -lower        lower limit for dot intensity (in %)
  -upper        upper limit for dot intensity (in %)
  -greyscale    greyscale start value (in %)

Miscellaneous:
  -silent       generate no output (except error messages)


Best regards,
Thomas Rattei

**Comment by rattei** [comment] 2021-12-20 09:58
Same, of course, with Gepard 2.1:

java -cp Gepard-2.1.jar org.gepard.client.cmdline.CommandLine

Gepard 2.0 - command line mode

Reference:
Krumsiek J, Arnold R, Rattei T
Gepard: A rapid and sensitive tool for creating dotplots on genome scale.
Bioinformatics 2007; 23(8): 1026-8. PMID: 17309896

Parameters are supplied as -name value

Required parameters:
  -seq:        the sequences, seperated by spaces. The first gets paired to the second, third to fourth and so on.
  -matrix:      substitution matrix file
  -outfile:     output file name

Dotplot image parameters:
  -maxwidth:    maximum width of the generated image (default: 750)
  -maxheight:   maximum height of the generated image (default: 750)
  -zoom:        specify a zoom factor for the dotplot
  note: you can only use maxwidth/maxheight OR zoom
        when using maxwidth/maxheight the program tries to generate the largest
        possible dotplot within the given bounds
  -format:      output format, one of:  'png', 'jpg', 'bmp' (default:PNG)

Dotplot computation parameters:
  -secondcomp   use complementary of second sequence
  -word:        word length for suffix array mode (default: 10)
  -window:      window size for ordinary dotplot mode (default: 0)
  if a window value and no word value is specified, word=0 is assumed

Suffix array parameters:
  -safile       load suffix array from file instead of calculating it
  -sasecondseq  the suffix array is for the second sequence
  if -sasecondseq is NOT specified, the suffix array will be used for first sequence

Coordinate parameters (absolute values of % values)
  -from1,-to1   coordinates of first sequence
  -from2,-to2   coordinates of second sequence
  if these parameters are not specified the full sequence will be used

Display parameters:
  -lower        lower limit for dot intensity (in %)
  -upper        upper limit for dot intensity (in %)
  -greyscale    greyscale start value (in %)
Sequence alignment
  -align        alignment algorythm (can be either Smith-Wateman or Needleman-Wunsch)
  -alignstart1  start coordinate of 1st sequence
  -alignstart2  start coordinate of 2nd sequence
  -alignwindow  window length

Miscellaneous:
  -silent       generate no output (except error messages)

**Comment by duhuipeng** [comment] 2021-12-20 10:28
Dear author 
![image](https://user-images.githubusercontent.com/58722433/146752334-bb362b88-b60b-457e-b680-7afb4a020b04.png)
I compared the results for the centromeric regions of chromosome X in the two species,Why is my result looking like this from the above?
The results in human centromeres are as follows:
![image](https://user-images.githubusercontent.com/58722433/146752729-908ec671-7234-49c0-a403-d9112bff20d8.png)
Where do I go wrong, and how can I modify it to achieve the effect of the article  in human

**Comment by duhuipeng** [comment] 2021-12-20 10:29
Each centromeric region is approximately 5Mb in different species

**Closed as completed** 2021-12-20 12:45 UTC

**Comment by rattei** [comment] 2021-12-20 12:49
Please find the jar files of Gepard 1.40 and Gepard 2.1 here in the GitHub repository (folder dist).

We have deleted the unrelated comments above. Display parameters can be adjusted using the command line parameters -lower, -upper, -greyscale. Please make use of these parameters.

The issue seems to be solved. We therefore close it now.

**Comment by duhuipeng** [comment] 2021-12-20 13:28
Dear author

The alignment of centromeric areas, what type of matrice is generally suitable,
 this picture of the article is too vague, I cannot see what the pattern he chose is in human article(as follow)
![image](https://user-images.githubusercontent.com/58722433/146774078-e380b94a-aa85-49c0-8472-7dee5dde10dc.png)
Colud you say the parameters of human centromeres for this picture?I want to follow their parameters to try it

Best
HuipengDu

**Comment by duhuipeng** [comment] 2021-12-20 13:42
![image](https://user-images.githubusercontent.com/58722433/146775918-d1254d86-5bc5-42d1-bfb4-111d78d30fba.png)
![image](https://user-images.githubusercontent.com/58722433/146776235-098244b1-fc10-49e3-9f87-23dadbaa8b84.png)

Why do I adjust such a high ratio in the centromere region or is it all black?What else do I need to do with it?Any change to the matrices mode?

**Comment by rattei** [comment] 2021-12-20 13:43
Display parameters can be adjusted using the command line parameters -lower, -upper, -greyscale. Please make use of these parameters.

**Comment by duhuipeng** [comment] 2021-12-20 13:45
I used ,That is the screenshot above

**Comment by duhuipeng** [comment] 2021-12-20 13:49
Dear author
Is it my mode matrices to adjust? My sequence is the sequence of the centromeric region. Could you suggest what mode to use?

Best
HuipengDu

**Comment by duhuipeng** [comment] 2021-12-21 01:33
Dear author
Could you give some suggestions on yesterday's question?
Best
HuipengDU
